FROM php:7.4-fpm-alpine

RUN apk update
RUN apk add zip unzip
RUN apk add wget
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet 
RUN mv composer.phar /usr/local/bin/composer

WORKDIR /app

ENTRYPOINT composer install && sh